// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LGRjli13QhNgVHz4wIx8W1VTFyN7mYo',
    appId: '1:22804410519:web:f54968ef091fc31ed179d2',
    messagingSenderId: '22804410519',
    projectId: 'cocktailer-4dc54',
    authDomain: 'cocktailer-4dc54.firebaseapp.com',
    storageBucket: 'cocktailer-4dc54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlNMdxG3MGviwzd5H-vRXqQRbPh5KpMBk',
    appId: '1:22804410519:android:d4bec970550ae4a4d179d2',
    messagingSenderId: '22804410519',
    projectId: 'cocktailer-4dc54',
    storageBucket: 'cocktailer-4dc54.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV8iiRMP85dSzlFOFYsUbIDuRPX64w57c',
    appId: '1:22804410519:ios:772e536ba5cbdffbd179d2',
    messagingSenderId: '22804410519',
    projectId: 'cocktailer-4dc54',
    storageBucket: 'cocktailer-4dc54.firebasestorage.app',
    iosBundleId: 'com.example.cocktailer',
  );
}
